---
- name: Set timezone to {{tzone}}
  win_timezone:
    timezone: "{{tzone}}"

- name: Get NTP server list
  win_shell: W32tm /query /source
  register: ntp_list

- name: currnet configured ntp server list is
  debug:
    msg: "{{ntp_list.stdout|trim}}"

- name: Set NTP with correct ip or hostname
  win_shell: w32tm /config /update /manualpeerlist:"{{ntp_server}}" /syncfromflags:manual /reliable:yes
  when: (ntp_list.stdout|trim) != ntp_server

- name: Restart w32time service
  win_service:
        name: w32time
        state: restarted
  when: (ntp_list.stdout|trim) != ntp_server



